version: '3'

services:
  app:
    environment:
      NODOS_HOST: "127.0.0.1"
      NODOS_PORT: "8080"
    command: npm start

  caddy:
    image: caddy:alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - app
