version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
