version: '3'

services:
  app:
    environment:
      NODOS_DB_HOSTNAME: db
      NODOS_DB_USERNAME: postgres
      NODOS_DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
